[build-system]
requires = [
    "h5py",
    "numpy",
    "tqdm",
    "hatchling"
    ]
build-backend = "hatchling.build"

[project]
name = "eagle_database"
version = "2022.1"
author = "Victor Forouhar Moreno"
author_email = "victor.j.forouhar@durham.ac.uk"

